# Sources
DIR_SOURCES := libnsfb.c frontend.c frontend_sdl.c plot.c plot_util.c plotters.c 32bpp_plotters.c 16bpp_plotters.c 8bpp_plotters.c

#frontend_linux.c

include build/makefiles/Makefile.subdir
